<?php
$lang['page_meta_title'] = 'Étude de cas Piwigo : une photothèque pour une école d\'ingénieurs française';
$lang['page_meta_description'] = 'Collaboration, performance : pourquoi le service Communication d\'une école d\'ingénieurs française a choisi Piwigo pour gérer sa photothèque.';

$lang['porg_cases_icam_title'] = 'Une photothèque partagée pour les campus de l\'Icam';
$lang['porg_cases_icam_description'] = 'L\'Icam (Institut Catholique d\'Arts et Métiers) est une école d\'ingénieurs créée en 1898 à Lille, qui compte aujourd\'hui 6 sites en France et 5 sites à l\'étranger. En France, elle diplôme chaque année plus de 600 ingénieurs et propose également une large offre de formation professionnelle ainsi qu\'un ensemble de services de R&D (recherche et développement).';

$lang['porg_cases_icam_challenge_title'] = 'Le défi : centraliser les données';
$lang['porg_cases_icam_challenge_description'] = 'Germain Dutilleul, responsable de la communication de l\'Icam, anime les équipes communication des différents campus de l\'école. À son arrivée à l\'Icam, chaque école gérait sa propre photothèque sur un serveur local et partageait les photos vers l\'extérieur sur un espace web. Le rôle des photos est central dans la communication de l\'Icam : les nombreux sites web et réseaux sociaux doivent être alimentés en permanence avec des visuels de qualité et à jour. Il fallait donc s\'orienter vers une photothèque partagée entre les 11 campus, afin de disposer d\'un référentiel unique tout en gérant finement les accès utilisateurs, les crédits et les droits d\'utilisation des images.';

$lang['porg_cases_icam_choice_description'] = 'Pour créer cette photothèque partagée, il fallait un outil complet fonctionnellement et abordable. Il fallait également un support utilisateur réactif, de proximité et francophone. Utilisateur de la solution open source Piwigo depuis des années, Germain Dutilleul s\'est naturellement tourné vers Piwigo.com, qui représentait le compromis idéal entre les outils de partage de photos aux fonctionnalités limitées (Flickr, Google Photos...) et les solutions coûteuses de gestion des médias numériques.';
$lang['porg_cases_icam_choice_text'] = 'Pour les fonctionnalités complètes, le support réactif et le prix très compétitif : je recommande Piwigo avec plaisir !';

$lang['porg_cases_icam_benefits_description'] = 'Aujourd\'hui, Piwigo est utilisé à l\'Icam par une dizaine d\'utilisateurs réguliers et une quinzaine d\'utilisateurs occasionnels. Germain et les référents communication de chaque campus alimentent la photothèque ; des prestataires externes (graphistes, photographes, vidéastes...) peuvent aussi disposer d\'un accès personnalisé pour déposer ou consulter des contenus.';
$lang['porg_cases_icam_benefits_text'] = 'Depuis la mise en place de notre Piwigo, notre organisation de travail est plus efficace. Nous n\'avons plus de problèmes de doublons et nous gagnons beaucoup de temps pour retrouver les photos dont nous avons besoin. Le partage avec les prestataires est également facilité et ils sont plus autonomes, tout le monde y gagne du temps. Nous avons structuré la gestion de la photothèque et cela contribue à notre démarche qualité.';
$lang['porg_cases_icam_benefits_person'] = 'Responsable de la communication de l\'Icam';
