<?php
$lang['page_meta_title'] = 'Étude de cas Piwigo : une photothèque d\'entreprise pour ECT';
$lang['page_meta_description'] = 'Gestion des médias numériques chez ECT : une photothèque ergonomique et collaborative pour gérer la banque d\'images de l\'entreprise.';

$lang['porg_cases_ect_title'] = 'Une photothèque collaborative et ergonomique pour ECT';
$lang['porg_cases_ect_description'] = 'ECT est une entreprise de 150 salariés dont le métier est la gestion des terres excavées et l\'aménagement du territoire. ECT récupère les terres excavées des chantiers de construction et les valorise en créant des aménagements durables en concertation avec les collectivités locales : parcs paysagers, fermes urbaines, merlons antibruit, aménagement de parcs photovoltaïques, etc.';

$lang['porg_cases_ect_challenge_title'] = 'Le défi : une photothèque ergonomique, collaborative et personnalisable';
$lang['porg_cases_ect_challenge_description'] = 'Lors de la création du service communication d\'ECT en 2017, l\'une des premières missions a été de constituer la banque d\'images de l\'entreprise. La photographie joue en effet un rôle fondamental dans la communication d\'ECT. Les photos servent bien sûr à réaliser tous les supports de communication (flyers, brochures, sites web, réseaux sociaux...). Mais la photothèque est aussi la mémoire de l\'entreprise. Des photos avant/après sont prises sur le terrain à chaque chantier. La photographie est pour ECT un moyen d\'expliquer concrètement son métier et de valoriser son savoir-faire.<br><br>Aussi, lorsque Sophie A, directrice de la communication, et Cindy D, responsable de la communication, ont commencé à constituer cette banque d\'images, elles ont rapidement ressenti le besoin d\'un logiciel de photothèque pour héberger, classer, trier et partager les photos.<br><br>Les images étaient jusqu\'alors stockées sur un serveur de fichiers partagé en interne. Pour les partager en dehors de l\'entreprise, il fallait passer par des liens WeTransfer ou saturer les boîtes mail des interlocuteurs. Quand les membres de l\'équipe cherchaient une photo, ils n\'étaient jamais sûrs d\'avoir le droit de l\'utiliser. La recherche dans l\'arborescence de fichiers était longue et fastidieuse.';

$lang['porg_cases_ect_choice_description'] = 'L\'équipe communication d\'ECT a donc établi une sélection de logiciels de photothèque susceptibles de répondre à ses besoins. Le choix final s\'est porté sur Piwigo, et ce pour plusieurs raisons : son ergonomie, sa simplicité d\'utilisation et son caractère personnalisable.';
$lang['porg_cases_ect_choice_text'] = 'Piwigo est beaucoup plus convivial que notre ancien système de fichiers. Les tags nous permettent de classer les photos plus facilement et de retrouver en quelques clics les images dont nous avons besoin.';

$lang['porg_cases_ect_benefits_description'] = 'Le gain le plus évident pour l\'équipe, c\'est le temps. Au moment de la mise en place de Piwigo, l\'équipe a pris le temps de réfléchir à son organisation. Elle a choisi d\'utiliser les tags pour classer les photos et les retrouver facilement, et de renseigner systématiquement les crédits afin de savoir quelles photos sont utilisables.<br>Aujourd\'hui, une vingtaine de personnes utilisent Piwigo dans l\'entreprise. Des partenaires externes ont également accès à l\'outil : les photographes qui travaillent pour ECT et l\'agence de communication. Chacun dispose de son accès personnel et ne peut consulter que les albums pour lesquels il a les permissions. La prochaine étape ? Utiliser l\'application mobile Piwigo pour simplifier les prises de vue sur le terrain !';
$lang['porg_cases_ect_benefits_text'] = 'Depuis la mise en place de Piwigo, nous perdons beaucoup moins de temps à chercher les photos dont nous avons besoin, c\'est instantané, nous sommes toujours à jour. Et puis le service support est formidable. On n\'est pas laissé seul une fois le logiciel installé, il y a toujours quelqu\'un pour répondre à nos questions et proposer des solutions rapidement. Je recommande Piwigo sans réserve !';
$lang['porg_cases_ect_benefits_person'] = 'Responsable Communication et Marketing';
