<?php
$lang['page_meta_title'] = 'Étude de cas Piwigo : une photothèque d\'entreprise pour ECT';
$lang['page_meta_description'] = 'Gestion des médias numériques chez ECT : une photothèque ergonomique et collaborative pour gérer la banque d\'images de l\'entreprise.';

$lang['porg_cases_ect_title'] = 'ECT : mise en place d’une photothèque collaborative et ergonomique';
$lang['porg_cases_ect_description'] = 'ECT est une entreprise de 150 collaborateurs dont le métier est la valorisation des terres excavées et l\'aménagement du territoire. ECT récupère les terres excavées des chantiers du bâtiment et des travaux publics en Île-de-France et les valorise en créant, en concertation avec les collectivités locales, des aménagements durables : parcs paysagers, fermes urbaines, aménagements phoniques, parcs photovoltaïques…';

$lang['porg_cases_ect_challenge_title'] = 'Le besoin : une photothèque ergonomique, collaborative et personnalisable';
$lang['porg_cases_ect_challenge_description'] = 'Lors de la création du service communication d\'ECT en 2017, l\'une des premières missions a été de constituer la banque d\'images de l\'entreprise. La photographie joue en effet un rôle fondamental dans la communication d\'ECT. Les photos servent à créer tous les supports de communication (flyers, plaquettes, site Internet, réseaux sociaux…), mais la photothèque constitue également la mémoire de l\'entreprise. Sur chaque chantier, des photos avant/après sont prises sur le terrain. La photographie permet ainsi à ECT d\'expliquer concrètement son métier et de valoriser son savoir-faire.<br><br>Lorsque Sophie A., directrice de la communication, et Cindy D., chargée de communication, ont commencé à constituer cette banque d\'images, elles ont rapidement ressenti le besoin d\'un logiciel de photothèque pour héberger, classer, trier et partager les photos.<br><br>Jusqu\'alors, les images étaient stockées sur un serveur de fichiers partagé en interne. Pour les transmettre à l\'extérieur de l\'entreprise, il fallait utiliser des liens WeTransfer ou surcharger les boîtes mail des interlocuteurs. Lorsqu\'un membre de l\'équipe cherchait une photo, il n\'était jamais certain d\'avoir le droit de l\'utiliser. La recherche dans l\'arborescence de fichiers était longue et fastidieuse.';

$lang['porg_cases_ect_choice_description'] = 'L\'équipe communication d\'ECT a donc sélectionné plusieurs logiciels de photothèque susceptibles de répondre à ses besoins. Son choix s\'est finalement porté sur Piwigo pour plusieurs raisons : son ergonomie, sa simplicité d\'utilisation et ses possibilités de personnalisation.';
$lang['porg_cases_ect_choice_text'] = 'Piwigo est beaucoup plus convivial que notre ancienne organisation. Les tags nous permettent de classer les photos plus facilement et de retrouver en quelques clics les images dont nous avons besoin.';

$lang['porg_cases_ect_benefits_description'] = 'Pour l\'équipe, le gain le plus évident est le temps gagné. Lors de la mise en place de Piwigo, elle a pris le temps de réfléchir à son organisation. Elle a choisi d\'utiliser les tags pour classer les photos et les retrouver facilement, et de renseigner systématiquement les crédits afin de savoir quelles images peuvent être utilisées.<br><br>Aujourd\'hui, une vingtaine de personnes utilisent Piwigo au sein de l\'entreprise. Des partenaires externes ont également accès à l\'outil, notamment les photographes qui travaillent pour ECT et l\'agence de communication. Chacun dispose d\'un accès personnel et ne peut consulter que les albums pour lesquels il dispose des autorisations nécessaires. La prochaine étape ? Utiliser l\'application mobile Piwigo pour simplifier les prises de vue sur le terrain !';
$lang['porg_cases_ect_benefits_text'] = 'Depuis la mise en place de Piwigo, nous perdons beaucoup moins de temps à chercher les photos dont nous avons besoin : c\'est immédiat et nous sommes toujours à jour. De plus, le service support est formidable. Nous ne sommes pas laissés seuls une fois le logiciel mis en place : il y a toujours quelqu\'un pour répondre à nos questions et proposer rapidement des solutions. Je recommande Piwigo sans réserve !';
$lang['porg_cases_ect_benefits_person'] = 'Chargée de communication et marketing';
