<?php
$lang['page_meta_title'] = 'Étude de cas Piwigo : un gestionnaire de médias numériques pour Wessex Water';
$lang['page_meta_description'] = 'Wessex Water a choisi Piwigo pour centraliser et sécuriser son patrimoine numérique avec une solution de DAM simple et abordable.';

$lang['porg_cases_wessex_title'] = 'Wessex Water a choisi Piwigo pour la gestion de son patrimoine numérique';
$lang['porg_cases_wessex_description'] = '<a class="orange-text" href="https://www.wessexwater.co.uk" target="_blank">Wessex Water</a> est une entreprise de distribution d\'eau et d\'assainissement qui dessert 2,8 millions de clients dans le sud-ouest de l\'Angleterre et emploie environ 3 500 personnes.';

$lang['porg_cases_wessex_challenge_title'] = 'Le besoin : une photothèque centralisée et sécurisée pour les images de l\'entreprise';
$lang['porg_cases_wessex_challenge_description'] = 'Wessex Water utilise de nombreux médias numériques, en interne comme en externe. Les photos et les vidéos sont exploitées par tous les services pour des usages variés : intranet, affichage dynamique, présentations, sites web, événements, campagnes de relations presse et réseaux sociaux.<br><br>Avant Piwigo, ces contenus étaient dispersés entre de multiples emplacements : ordinateurs, SharePoint, OneDrive, Outlook, lecteurs réseau, disques locaux et CD.<br><br>Lorsqu\'une personne avait besoin d\'une image, elle ne savait pas toujours à qui s\'adresser ni où la chercher. Il était également difficile d\'identifier la bonne version d\'un fichier, tandis que la gestion du RGPD et des droits à l\'image était complexe.';
$lang['porg_cases_wessex_challenge_text'] = 'Nous avions un véritable problème de contrôle qualité et peinions à retrouver et à organiser l\'ensemble de nos médias numériques.';

$lang['porg_cases_wessex_choice_description'] = 'Chez Wessex Water, l\'équipe digitale, composée de 10 personnes, est responsable des outils et des médias numériques : gestion des canaux, contenus, conception numérique, production vidéo… Elle travaille avec tous les autres services afin de comprendre leurs besoins en matière de contenus et de médias.<br><br>En 2020, l\'équipe a décidé de rechercher un logiciel de Digital Asset Management (DAM), ou gestion des ressources numériques, afin de structurer et d\'organiser la diffusion des médias dans toute l\'entreprise.<br><br>Après avoir étudié plusieurs solutions de DAM, elle a découvert Piwigo sur la recommandation d\'une collectivité qui l\'utilisait déjà.';
$lang['porg_cases_wessex_choice_text'] = 'Nous ne voulions pas d\'une solution trop complexe. Piwigo était simple à utiliser, rapide à mettre en place et son prix constituait un véritable avantage. Il n\'existait aucune solution équivalente sur le marché à ce niveau de prix.';

$lang['porg_cases_wessex_deploy_title'] = 'Un déploiement facile';
$lang['porg_cases_wessex_deploy_description'] = 'Avant de déployer Piwigo, l\'équipe digitale a mené un important travail de fond afin de définir les règles de classement ainsi que le processus de soumission et de publication des ressources dans la galerie. Une liste de contrôle et des règles d\'attribution des tags ont notamment été établies.';
$lang['porg_cases_wessex_deploy_text'] = 'Il nous a fallu trois mois pour définir l\'organisation. L\'essentiel du travail ne concernait pas Piwigo, mais la définition des processus et la communication. Les utilisateurs n\'ont rencontré aucune difficulté pour adopter Piwigo : la solution est vraiment simple à utiliser.';

$lang['porg_cases_wessex_benefits_description'] = 'Lors de la rédaction de cette étude de cas, le Piwigo de Wessex Water comptait 50 utilisateurs au sein de l\'entreprise, dont 4 administrateurs. Le déploiement se faisait progressivement : de nombreux salariés ne disposaient pas encore d\'un accès direct à la plateforme et devaient toujours transmettre une demande pour obtenir un média précis, mais l\'équipe digitale étendait peu à peu l\'utilisation de Piwigo à toute l\'entreprise.<br><br>Les bénéfices étaient déjà nombreux. Disposer d\'un catalogue centralisé de tous les médias numériques, associé à un moteur de recherche performant, permettait de retrouver rapidement les contenus recherchés. Il n\'y avait plus de risque de doublon ni de problème de version. Les données étaient sécurisées et le risque de perdre des fichiers avait disparu.';
$lang['porg_cases_wessex_benefits_text'] = 'Avec Piwigo, nous obtenons un excellent rapport qualité-prix. Le support est vraiment efficace et le produit est facile à utiliser.';
$lang['porg_cases_wessex_benefits_person'] = 'Digital Delivery Manager';
$lang['porg_cases_wessex_benefits_structure'] = 'Wessex Water';
