<?php
$lang['page_meta_title'] = 'Piwigo Fallstudie: eine unternehmensweite Mediathek für ECT';
$lang['page_meta_description'] = 'Digital Asset Management bei ECT: eine ergonomische und kollaborative Mediathek für die Bilddatenbank des Unternehmens.';

$lang['porg_cases_ect_title'] = 'Eine kollaborative und ergonomische Mediathek für ECT';
$lang['porg_cases_ect_description'] = 'ECT ist ein Unternehmen mit 150 Mitarbeitenden, dessen Geschäft die Verwertung von Aushubmaterial und die Flächenentwicklung ist. ECT nimmt Aushub von Baustellen auf und verwertet ihn, indem es gemeinsam mit Kommunen nachhaltige Anlagen schafft: Landschaftsparks, Stadtfarmen, Lärmschutzwälle, Photovoltaikparks und mehr.';

$lang['porg_cases_ect_challenge_title'] = 'Die Herausforderung: eine ergonomische, kollaborative und anpassbare Mediathek';
$lang['porg_cases_ect_challenge_description'] = 'Als 2017 die Kommunikationsabteilung von ECT aufgebaut wurde, gehörte der Aufbau der unternehmenseigenen Bilddatenbank zu den ersten Aufgaben. Fotografie spielt in der Kommunikation von ECT eine grundlegende Rolle. Die Fotos dienen natürlich der Gestaltung sämtlicher Kommunikationsmittel (Flyer, Broschüren, Websites, soziale Netzwerke...). Die Mediathek ist aber auch das Gedächtnis des Unternehmens. Auf jeder Baustelle entstehen Vorher-Nachher-Aufnahmen. Über Fotografie kann ECT sein Geschäft anschaulich erklären und sein Können zeigen.<br><br>Als Sophie A, Kommunikationsleiterin, und Cindy D, Kommunikationsmanagerin, mit dem Aufbau dieser Bilddatenbank begannen, wurde ihnen schnell klar, dass sie eine Mediathek-Software brauchten, um Fotos abzulegen, zu klassifizieren, zu sortieren und zu teilen.<br><br>Bis dahin lagen die Bilder auf einem intern geteilten Dateiserver. Um sie außerhalb des Unternehmens zu teilen, musste man auf WeTransfer-Links zurückgreifen oder die Postfächer der Beteiligten überladen. Wenn Teammitglieder ein Foto suchten, waren sie nie sicher, ob sie es verwenden durften. Die Suche im Dateibaum war langwierig und mühsam.';

$lang['porg_cases_ect_choice_description'] = 'Das Kommunikationsteam von ECT stellte daher eine Auswahl an Mediathek-Programmen zusammen, die den eigenen Anforderungen genügen konnten. Die Wahl fiel schließlich auf Piwigo, und das aus mehreren Gründen: die Ergonomie, die einfache Bedienung und die Anpassbarkeit.';
$lang['porg_cases_ect_choice_text'] = 'Piwigo ist deutlich angenehmer als unser altes Dateisystem. Die Tags erlauben uns, Fotos leichter zu ordnen und die benötigten Bilder in wenigen Klicks zu finden.';

$lang['porg_cases_ect_benefits_description'] = 'Der offensichtlichste Gewinn für das Team ist die Zeitersparnis. Bei der Einführung von Piwigo hat sich das Team bewusst Zeit genommen, um seine Organisation zu durchdenken. Es entschied sich dafür, Fotos über Tags zu ordnen und so leicht wiederzufinden, und die Bildnachweise konsequent zu erfassen, um zu wissen, welche Fotos verwendet werden dürfen.<br>Heute nutzen rund zwanzig Personen im Unternehmen Piwigo. Auch externe Partner haben Zugang zum Werkzeug: die für ECT tätigen Fotografen und die Kommunikationsagentur. Jeder hat seinen persönlichen Zugang und sieht nur die Alben, für die er berechtigt ist. Der nächste Schritt? Die mobile Piwigo App nutzen, um die Aufnahmen vor Ort zu vereinfachen!';
$lang['porg_cases_ect_benefits_text'] = 'Seit der Einführung von Piwigo verlieren wir viel weniger Zeit bei der Suche nach den benötigten Fotos, es geht sofort, wir sind immer auf dem aktuellen Stand. Und der Support ist großartig. Man wird nach der Einführung nicht alleingelassen, es ist immer jemand da, der unsere Fragen beantwortet und schnell Lösungen vorschlägt. Ich empfehle Piwigo uneingeschränkt weiter!';
$lang['porg_cases_ect_benefits_person'] = 'Leitung Kommunikation und Marketing';
