<?php

$lang['porg_about_us_title'] = 'Open source photo management software <br><span class="orange-text">since 2002</span>';
$lang['porg_about_us_desc'] = 'For more than 20 years, Piwigo has remained true to the same idea: giving people full control over their photo and video collections through open source software that is independent, sustainable and built around real user needs.';

$lang['porg_about_us_years'] = 'of continuous development';
$lang['porg_about_us_installations'] = 'installations worldwide';
$lang['porg_about_us_downloads'] = 'downloads';
$lang['porg_about_us_extensions'] = 'extensions';
$lang['porg_about_us_languages'] = 'languages';

$lang['porg_about_us_desc_title'] = 'Mission and values';
$lang['porg_about_us_desc_title_card1'] = 'Open source';
$lang['porg_about_us_desc_desc_card1'] = 'We build open source software that helps people and organizations manage their photo and video collections.';
$lang['porg_about_us_desc_title_card2'] = 'Freedom and control';
$lang['porg_about_us_desc_desc_card2'] = 'We believe photo management should be powerful, sustainable and accessible, without forcing users into proprietary ecosystems or limiting their control over their own data.';
$lang['porg_about_us_desc_title_card3'] = 'Users before technology';
$lang['porg_about_us_desc_desc_card3'] = 'We focus on building the best possible experience for our users, putting usability and real-world needs ahead of technology for technology’s sake.';

$lang['porg_about_us_beginning_title'] = 'How it all started';
$lang['porg_about_us_beginning_desc'] = 'Back in 2001, while studying computer science, Pierrick Le Gall bought his first digital camera. Looking for a way to share photos with family and friends, he decided to combine his passion for photography and software development.<br><br>In 2002, he released PHPWebGallery as an open source project. What started as a personal solution for sharing photos would eventually become Piwigo, a platform used by individuals and organizations around the world.';

$lang['porg_about_us_open_title'] = 'Open source at heart';
$lang['porg_about_us_open_desc'] = 'Piwigo is open source software released under the GPL license.<br><br><span class="orange-text">Anyone can download it, install it, customize it and contribute to its development.</span><br><br>Over the years, hundreds of contributors have helped improve Piwigo through code, translations, documentation, support and feedback. This collaborative spirit remains an essential part of the project today.';

$lang['porg_about_us_inde_title'] = 'Independent and European';
$lang['porg_about_us_inde_desc'] = 'Piwigo is developed in France by a company owned by its founder and team members.<br><br>Our growth is funded by our customers, not by advertising or external investors. This allows us to focus on long-term sustainability and the needs of our users rather than short-term growth targets.<br><br><span class="green-text">We remain free to build Piwigo according to our values and our vision of open source software.</span>';

$lang['porg_about_us_team_title'] = 'Built by a professional team, supported by a community';
$lang['porg_about_us_team_subtitle'] = 'Piwigo is maintained by a dedicated team based in France.';
$lang['porg_about_us_team_text1'] = 'Alongside the core team, contributors from around the world help improve Piwigo through bug fixes, plugins, translations, testing, documentation and community support.';
$lang['porg_about_us_team_text2'] = 'The community has always been an essential part of the project. Since the beginning, more than 282,000 messages have been exchanged on the forum, helping users solve problems, share ideas and help shape the future of Piwigo.';
$lang['porg_about_us_team_text3'] = 'Together, the team and the community ensure that Piwigo remains active, reliable and continuously evolving.';
$lang['Meet our staff'] = 'Meet our staff';
$lang['Founder & Lead Developer'] = 'Founder & Lead Developer';
$lang['Support & Plugin Developer'] = 'Support & Plugin Developer';
$lang['Developer'] = 'Developer';
$lang['Marketing'] = 'Marketing';
$lang['UX/UI Designer'] = 'UX/UI Designer';
$lang['Finance'] = 'Finance';

$lang['porg_about_us_model_title'] = 'A sustainable <br>business model';
$lang['porg_about_us_model_desc'] = 'Unlike many open source projects, Piwigo benefits from a sustainable business model that funds its long-term development.';
$lang['porg_about_us_model_title1'] = 'Piwigo Cloud';
$lang['porg_about_us_model_desc1'] = 'Piwigo Cloud subscriptions finance the development of the open source project.<br><br>Revenue generated by Piwigo Cloud allows the team to work full-time on improving Piwigo, maintaining the software and supporting users.<br><br>By choosing Piwigo Cloud, customers directly contribute to the future of the project.';
$lang['porg_about_us_model_title2'] = 'Professional services';
$lang['porg_about_us_model_desc2'] = 'Some organizations rely on the Piwigo team and partners for consulting, custom developments and specific integrations. These collaborations often benefit the wider community through improvements contributed back to the project.';
$lang['porg_about_us_model_title3'] = 'Community donations';
$lang['porg_about_us_model_desc3'] = 'We also collect donations that help cover community-related expenses such as infrastructure, domain names and mobile application distribution.';
$lang['porg_about_us_model_title4'] = 'A virtuous circle';
$lang['porg_about_us_model_desc4'] = 'The success of Piwigo Cloud helps fund the development of Piwigo Open Source.<br><br>In return, improvements made to the software benefit both self-hosted users and Piwigo Cloud customers.<br>The success of one strengthens the other.';

$lang['porg_about_us_milestone_2002'] = 'Piwigo is born under the name PHPWebGallery, as a personal project created by Pierrick Le Gall.';
$lang['porg_about_us_milestone_2007'] = 'The plugin system is introduced, opening the door to customization and community contributions.';
$lang['porg_about_us_milestone_2009'] = 'PHPWebGallery becomes Piwigo, marking a new chapter in the project’s evolution.';
$lang['porg_about_us_milestone_2010'] = 'Launch of Piwigo.com, making Piwigo available as a hosted solution.';
$lang['porg_about_us_milestone_2011'] = 'The first mobile applications for iOS and Android are released.';
$lang['porg_about_us_milestone_2015'] = 'Piwigo moves its source code and development workflow to GitHub.';
$lang['porg_about_us_milestone_2017'] = 'The team grows, strengthening Piwigo’s professional development and long-term sustainability.';
$lang['porg_about_us_milestone_2018'] = 'Piwigo launches a major UX/UI redesign project, bringing designers into the product development process.';
$lang['porg_about_us_milestone_2019'] = 'Growing adoption by businesses, public institutions and nonprofits leads Piwigo to expand its professional offerings.';
$lang['porg_about_us_milestone_2020'] = 'The shift to remote work highlights the value of Piwigo for distributed teams. Increased demand for collaborative photo management helps drive 30% growth in both 2020 and 2021.';
$lang['porg_about_us_milestone_2025'] = 'Piwigo launches its first AI initiatives, paving the way for new features focused on photo management and user productivity.';
$lang['porg_about_us_milestone_today'] = 'Piwigo is used by individuals and organizations around the world to manage, share and preserve their photo and video collections.';

$lang['porg_about_us_join_title'] = 'Join the adventure';
$lang['porg_about_us_join_desc'] = '<span class="orange-text strong-text">Piwigo exists thanks to its users, contributors, customers and partners.</span><br><br>Whether you want to contribute code, improve translations, report bugs, make a donation, or choose Piwigo Cloud for your organization, there are many ways to get involved.';
$lang['porg_about_us_join_title'] = 'Join the adventure';

?>