<?php
$lang['page_meta_title'] = 'Piwigo case study: a corporate photo library for ECT';
$lang['page_meta_description'] = 'Digital asset management for ECT : an ergonomic and collaborative photo library to manage the corporate image bank.';

$lang['porg_cases_ect_title'] = 'A collaborative and ergonomic photo library for ECT';
$lang['porg_cases_ect_description'] = 'ECT is a company with 150 employees, whose purpose is excavated ground management and land use planning. ECT recovers the excavated soil from construction sites, and valorizes it by creating sustainable developments in consultation with local authorities: landscape parks, urban farms, soundproofing, photovoltaic park development, etc.';

$lang['porg_cases_ect_challenge_title'] = 'The challenge: an ergonomic, collaborative and customizable photo library';
$lang['porg_cases_ect_challenge_description'] = 'When ECT’s communication department was created in 2017, one of the first tasks was to create the company’s corporate image bank. Indeed, photography has a fundamental role in ECT’s communication. The photos are of course used to create all communication media (flyers, brochures, websites, social networks...). But the photo library is also the company’s memory. Before and after photos are taken in the field during each construction site. Photography is a way for ECT to explain its business in concrete terms and to promote its know-how.<br><br>So when Sophie A, Communications Director, and Cindy D, Communications Manager, started creating this image bank, they quickly felt the need for a photo library software to host, classify, sort and share photos.<br><br>In fact, images were previously stored on an internally shared file server. To share them outside the company, it was necessary to use sharing links with WeTransfer, or to overload the mailboxes of the stakeholders. When team members were looking for a photo, they were never sure if they had the right to use it. The search in the file tree was long and tedious.';

$lang['porg_cases_ect_choice_description'] = 'The ECT communication team therefore made a selection of photo library softwares that could meet their needs. The final choice was Piwigo and for several reasons: its ergonomics, its ease of use, and its customizable nature.';
$lang['porg_cases_ect_choice_text'] = 'Piwigo is much more friendly than our old file system. Tags allow us to classify photos more easily and to find in a few clicks the images we need.';

$lang['porg_cases_ect_benefits_description'] = 'The most obvious gain for the team is saving time. When Piwigo was set up, the team took the time to think about its organization. They chose to use tags to classify photos and find them easily, and to systematically note credits in order to know which photos are usable.<br>Today, about twenty people within the company use Piwigo. External partners also have access to the tool: photographers working for ECT and the communication agency. Everyone has their own personal access, and can only view the albums to which they have the permissions. The next step? Use the Piwigo mobile application to simplify the field shooting process!';
$lang['porg_cases_ect_benefits_text'] = 'Since the implementation of Piwigo, we lose much less time looking for the photos we need, it’s instantaneous, we’re always up to date. Besides, the support service is great. We are not alone once the software is implemented, there is always someone to answer our questions and propose solutions in a short time. I recommend Piwigo without reservation!';
$lang['porg_cases_ect_benefits_person'] = 'Communication and Marketing Manager';
